//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadLinkSolution.DeadLinkSolutionGW {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gw.job.co.kr/DeadLinkSolutionGW.asmx", ConfigurationName="DeadLinkSolutionGW.DeadLinkSolutionGWSoap")]
    public interface DeadLinkSolutionGWSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw.job.co.kr/DeadLinkSolutionGW.asmx/GetLoadPattern", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLoadPattern(string strEncrypt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw.job.co.kr/DeadLinkSolutionGW.asmx/GetLoadPattern", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLoadPatternAsync(string strEncrypt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw.job.co.kr/DeadLinkSolutionGW.asmx/SaveToLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SaveToLog(string sourceSiteNm, int scan_cnt, int deadlink_cnt, string machineName, string strEncrypt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw.job.co.kr/DeadLinkSolutionGW.asmx/SaveToLog", ReplyAction="*")]
        System.Threading.Tasks.Task SaveToLogAsync(string sourceSiteNm, int scan_cnt, int deadlink_cnt, string machineName, string strEncrypt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw.job.co.kr/DeadLinkSolutionGW.asmx/SaveToDeadlinkLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SaveToDeadlinkLog(int jobPostNo, string linkurl, string type, string status, string message, string strEncrypt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw.job.co.kr/DeadLinkSolutionGW.asmx/SaveToDeadlinkLog", ReplyAction="*")]
        System.Threading.Tasks.Task SaveToDeadlinkLogAsync(int jobPostNo, string linkurl, string type, string status, string message, string strEncrypt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeadLinkSolutionGWSoapChannel : DeadLinkSolution.DeadLinkSolutionGW.DeadLinkSolutionGWSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeadLinkSolutionGWSoapClient : System.ServiceModel.ClientBase<DeadLinkSolution.DeadLinkSolutionGW.DeadLinkSolutionGWSoap>, DeadLinkSolution.DeadLinkSolutionGW.DeadLinkSolutionGWSoap {
        
        public DeadLinkSolutionGWSoapClient() {
        }
        
        public DeadLinkSolutionGWSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeadLinkSolutionGWSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeadLinkSolutionGWSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeadLinkSolutionGWSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetLoadPattern(string strEncrypt) {
            return base.Channel.GetLoadPattern(strEncrypt);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLoadPatternAsync(string strEncrypt) {
            return base.Channel.GetLoadPatternAsync(strEncrypt);
        }
        
        public void SaveToLog(string sourceSiteNm, int scan_cnt, int deadlink_cnt, string machineName, string strEncrypt) {
            base.Channel.SaveToLog(sourceSiteNm, scan_cnt, deadlink_cnt, machineName, strEncrypt);
        }
        
        public System.Threading.Tasks.Task SaveToLogAsync(string sourceSiteNm, int scan_cnt, int deadlink_cnt, string machineName, string strEncrypt) {
            return base.Channel.SaveToLogAsync(sourceSiteNm, scan_cnt, deadlink_cnt, machineName, strEncrypt);
        }
        
        public void SaveToDeadlinkLog(int jobPostNo, string linkurl, string type, string status, string message, string strEncrypt) {
            base.Channel.SaveToDeadlinkLog(jobPostNo, linkurl, type, status, message, strEncrypt);
        }
        
        public System.Threading.Tasks.Task SaveToDeadlinkLogAsync(int jobPostNo, string linkurl, string type, string status, string message, string strEncrypt) {
            return base.Channel.SaveToDeadlinkLogAsync(jobPostNo, linkurl, type, status, message, strEncrypt);
        }
    }
}
